---
name: Release please in GH
on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release-please:
        name: Prepare Release notes
        runs-on: ubuntu-latest
        outputs:
            released: ${{ steps.release-please.outputs.releases_created }}
        steps:
            - id: release-please
              uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.NATALIA_PAT }}
                  config-file: release-please-config.json
                  manifest-file: .release-please-manifest.json